routes/admin.php
<?php

Route::name('admin.')->group(function () {
    Route::group(['namespace' => 'Admin'], function() {
        // Dashboard
        Route::get('/', 'HomeController@index')->name('home');
    
        // Login
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    
        // Register
        // Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('admin.register');
        // Route::post('register', 'Auth\RegisterController@register');
    
        // Reset Password
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
    
        // Confirm Password
        Route::get('password/confirm', 'Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
        Route::post('password/confirm', 'Auth\ConfirmPasswordController@confirm');
    
        // Verify Email
        // Route::get('email/verify', 'Auth\VerificationController@show')->name('admin.verification.notice');
        // Route::get('email/verify/{id}/{hash}', 'Auth\VerificationController@verify')->name('admin.verification.verify');
        // Route::post('email/resend', 'Auth\VerificationController@resend')->name('admin.verification.resend');
    
    
        Route::group(['namespace' => 'AccountManager', 'middleware' => ['admin.auth']], function() {
            Route::resource('roles','RoleController');
            Route::resource('permissions','PermissionController');
            Route::resource('admin_manager','AdminController');
        });
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Example Routes
Route::view('/', 'landing');

// Route::match(['get', 'post'], '/dashboard', function(){
//     return view('dashboard');
// });
// Route::view('/pages/slick', 'pages.slick');
// Route::view('/pages/datatables', 'pages.datatables');
// Route::view('/pages/blank', 'pages.blank');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/AccountManager/PermissionController.php
<?php
namespace App\Http\Controllers\Admin\AccountManager;

use Illuminate\Http\Request;
use App\Http\Controllers\Admin\BaseController;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;


class PermissionController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('admin_permission:role-list|role-create|role-edit|role-delete', ['only' => ['index']]);
         $this->middleware('admin_permission:role-create', ['only' => ['create','store']]);
         $this->middleware('admin_permission:role-edit', ['only' => ['edit','update']]);
         $this->middleware('admin_permission:role-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $permissions = Permission::orderBy('id','DESC')->paginate(5);
        return view('admin.accounts.permissions.index',compact('permissions'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $guards = config('custom.guards');
        $roles = Role::get();
        return view('admin.accounts.permissions.create', compact('roles', 'guards'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:40',
        ]);


        $name = $request['name'];
        $permission = new Permission();
        $permission->name = $name;
        $permission->guard_name = $request->input('guard_name');
        $roles = $request->input('roles', []);

        $permission->save();
        if ($roles) {
            foreach ($roles as $role) {
                $r = Role::where(['id' => $role, 'guard_name' => $permission->guard_name])->first();
                $permission = Permission::where('name', '=', $name)->first();
                $permission && $r && $r->givePermissionTo($permission);
            }
        }

        return redirect()->route('admin.permissions.index')
                        ->with('success','Permission created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect('admin.permissions.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $guards = config('custom.guards');
        $permission = Permission::find($id);

        return view('admin.accounts.permissions.edit', compact('permission', 'guards'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $permission = Permission::findOrFail($id);
        $this->validate($request, [
            'name' => 'required|max:40',
        ]);

        $permission->name = $request->input('name');
        $permission->guard_name = $request->input('guard_name');
        $permission->save();

        return redirect()->route('admin.permissions.index')
                        ->with('success','Permission updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $permission = Permission::findOrFail($id);

        if ($permission->name == "roles_and_permissions") {
            return redirect()->route('admin.permissions.index')
                ->with('success', 'Can not delete this permission.');
        }

        $permission->delete();

        return redirect()->route('admin.permissions.index')
                        ->with('success','Permission deleted successfully');
    }
}

resources/views/admin/accounts/permissions/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                Create Permission <small class="font-size-base font-w400 text-muted">Permission</small>
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="{{ route('admin.home')}}">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="{{ route('admin.permissions.index')}}">Permission</a></li>
                    <li class="breadcrumb-item" aria-current="page">
                        <a class="link-fx" href="{{ route('admin.permissions.create') }}">Create Permission</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<div class="content">
    <div class="row">
        <div class="col-xl-12">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title">Create Permission</h3>
                </div>
                <div class="block-content block-content-full">
                    {{ Form::open(['route' => 'admin.permissions.store', 'method' => 'post']) }}
                        <div class="row push">
                            <div class="col-lg-8 col-xl-5">
                                <div class="form-group">
                                    {{ Form::label('permission_name', 'Name') }} <span class="text-danger">*</span>
                                    {{ Form::text('name', null, array('class' => 'form-control', 
                                        'id' => 'permission_name', 
                                        'placeholder' => 'Permission Name')) }}
                                </div>
                                <div class="form-group">
                                    {{ Form::label('permission_guard', 'Guard') }} <span class="text-danger">*</span>
                                    {{ Form::select('guard_name', $guards, null, array('class' => 'form-control', 'id' => 'permission_guard')) }}
                                </div>
                                @if(!$roles->isEmpty())
                                    <div class="form-group">
                                        <label>Assign Permission to Roles</label>
                                        @foreach ($roles as $role)
                                            <div class="form-check">
                                                {{ Form::checkbox('roles[]',  $role->id, null, ['id' => 'role_' . $role->id, 'class' => 'form-check-input']) }}
                                                {{ Form::label('role_' . $role->id, ucfirst($role->name), ['class' => 'form-check-label']) }}
                                            </div>
                                        @endforeach
                                    </div>
                                @endif
                                <hr>
                                <div class="form-group row">
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-block btn-primary">
                                            <i class="fa fa-fw fa-save mr-1"></i> Save
                                        </button>
                                    </div>
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-block btn-alt-secondary">
                                            <i class="fa fa-fw fa-times-circle mr-1"></i> Cancel
                                        </button>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    {{-- Todo update --}}
    <script type="text/javascript">
        var displayPermission = function () {
            if($('select[name=guard_name]').val() === 'admin'){
                $('.guard_user').hide();
                $('.guard_admin').show();
                $('.border-checkbox-section .guard_admin input').prop('disabled', false);
                $('.border-checkbox-section .guard_user input').prop('disabled', true);
                $('.border-checkbox-section .guard_user input').prop('checked', false);
            } else {
                $('.guard_user').show();
                $('.guard_admin').hide();
                $('.border-checkbox-section .guard_admin input').prop('disabled', true);
                $('.border-checkbox-section .guard_admin input').prop('checked', false);
                $('.border-checkbox-section .guard_user input').prop('disabled', false);
            }
            $('#permission_all').prop('checked', false);
        };

        $(document).ready(function () {
            displayPermission();
            $('select[name=guard_name]').change(displayPermission);
        });
    </script>
@endpush

resources/views/admin/accounts/permissions/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                Edit Permission <small class="font-size-base font-w400 text-muted">Permission</small>
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="{{ route('admin.home')}}">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="{{ route('admin.permissions.index')}}">Permission</a></li>
                    <li class="breadcrumb-item" aria-current="page">
                        <a class="link-fx" href="{{ route('admin.permissions.edit', $permission->id) }}">Edit Permission</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>


<div class="content">
    <div class="row">
        <div class="col-xl-12">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title">Create Permission</h3>
                </div>
                <div class="block-content block-content-full">
                    {{ Form::model($permission, ['route' => ['admin.permissions.update', $permission->id], 'method' => 'PUT']) }}
                        <div class="row push">
                            <div class="col-lg-8 col-xl-5">
                                <div class="form-group">
                                    {{ Form::label('permission_name', 'Name') }} <span class="text-danger">*</span>
                                    {{ Form::text('name', null, array('class' => 'form-control', 
                                        'id' => 'permission_name', 
                                        'placeholder' => 'Permission Name')) }}
                                </div>
                                <div class="form-group">
                                    {{ Form::label('permission_guard', 'Guard') }} <span class="text-danger">*</span>
                                    {{ Form::select('guard_name', $guards, null, array('class' => 'form-control', 'id' => 'permission_guard')) }}
                                </div>
                                <hr>
                                <div class="form-group row">
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-block btn-primary">
                                            <i class="fa fa-fw fa-save mr-1"></i> Update
                                        </button>
                                    </div>
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-block btn-alt-secondary">
                                            <i class="fa fa-fw fa-times-circle mr-1"></i> Cancel
                                        </button>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/accounts/permissions/index.blade.php
@extends('admin.layouts.app')

@push('css_before')
<link rel="stylesheet" href="{{ asset('/js/plugins/sweetalert2/sweetalert2.min.css')}}">
@endpush

@section('content')
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                Permission <small class="font-size-base font-w400 text-muted">Permission</small>
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">Dashboard</li>
                    <li class="breadcrumb-item" aria-current="page">
                        <a class="link-fx" href="">Permission</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<div class="content">
    <div class="row">
        <div class="col-xl-12">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title">Permission</h3>
                    <div class="block-options">
                        <div class="block-options-item">
                            <code>
                                <a href="{{ route('admin.permissions.create')}}" class="btn btn-primary">Add</a>
                            </code>
                        </div>
                    </div>
                </div>
                <div class="block-content">
                    <table class="table table-vcenter">
                        <thead>
                            <tr>
                                <th class="text-center" style="width: 50px;">#</th>
                                <th>Name</th>
                                <th class="d-none d-sm-table-cell">Guard</th>
                                <th class="text-center" style="width: 100px;">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($permissions as $permission)
                            <tr>
                                <th class="text-center" scope="row">1</th>
                                <td class="font-w600 font-size-sm">
                                    <a href="javascript void(0)">{{ $permission->name }}</a>
                                </td>
                                <td class="d-none d-sm-table-cell">
                                    <span class="badge badge-success">{{ $permission->guard_name }}</span>
                                </td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <a href="{{ route('admin.permissions.edit', $permission->id) }}" class="btn btn-sm btn-light" data-toggle="tooltip" title="Edit Permission">
                                            <i class="fa fa-fw fa-pencil-alt"></i>
                                        </a>
                                        <button type="button" class="btn btn-sm btn-light btn-delete-permission"
                                            data-permission_id="{{$permission->id}}"
                                            data-toggle="tooltip" 
                                            title="Remove Permission"
                                        >
                                            <i class="fa fa-fw fa-times"></i>
                                        </button>
                                        {!! Form::open(['method' => 'DELETE', 'route' => ['admin.permissions.destroy', $permission->id], 'id' => 'form-delete-' . $permission->id ]) !!}
                                        {!! Form::close() !!}
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

@push('scripts')
<!-- Page JS Plugins -->
<script src="{{ asset('/js/plugins/es6-promise/es6-promise.auto.min.js')}}"></script>
<script src="{{ asset('/js/plugins/sweetalert2/sweetalert2.min.js')}}"></script>

<script>
    $(function(){
        // Set default properties
        let toast = Swal.mixin({
            buttonsStyling: false,
            customClass: {
                confirmButton: 'btn btn-success m-1',
                cancelButton: 'btn btn-danger m-1',
                input: 'form-control'
            }
        });

        $(document).on('click', '.btn-delete-permission', function(){
            var id =  $(this).data('permission_id');
            toast.fire({
                title: 'Are you sure?',
                text: 'You will not be able to recover this permission!',
                icon: 'warning',
                showCancelButton: true,
                customClass: {
                    confirmButton: 'btn btn-danger m-1',
                    cancelButton: 'btn btn-secondary m-1'
                },
                confirmButtonText: 'Yes, delete it!',
                html: false,
                preConfirm: e => {
                    $('#form-delete-'+id).submit();
                }
            }).then(result => {
                if (result.value) {
                    toast.fire('Deleted!', 'Permission has been deleted.', 'success');
                    // result.dismiss can be 'overlay', 'cancel', 'close', 'esc', 'timer'
                } else if (result.dismiss === 'cancel') {
                    toast.fire('Cancelled', 'Permission is safe :)', 'error');
                }
            });
        });
    });
</script>
@endpush