routes/admin.php
<?php

Route::name('admin.')->group(function () {
    Route::group(['namespace' => 'Admin'], function() {
        // Dashboard
        Route::get('/', 'HomeController@index')->name('home');
    
        // Login
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    
        // Register
        // Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('admin.register');
        // Route::post('register', 'Auth\RegisterController@register');
    
        // Reset Password
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
    
        // Confirm Password
        Route::get('password/confirm', 'Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
        Route::post('password/confirm', 'Auth\ConfirmPasswordController@confirm');
    
        // Verify Email
        // Route::get('email/verify', 'Auth\VerificationController@show')->name('admin.verification.notice');
        // Route::get('email/verify/{id}/{hash}', 'Auth\VerificationController@verify')->name('admin.verification.verify');
        // Route::post('email/resend', 'Auth\VerificationController@resend')->name('admin.verification.resend');
    
    
        Route::group(['namespace' => 'AccountManager', 'middleware' => ['admin.auth']], function() {
            Route::resource('roles','RoleController');
            Route::resource('permissions','PermissionController');
            Route::resource('admin_manager','AdminController');
        });
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Example Routes
Route::view('/', 'landing');

// Route::match(['get', 'post'], '/dashboard', function(){
//     return view('dashboard');
// });
// Route::view('/pages/slick', 'pages.slick');
// Route::view('/pages/datatables', 'pages.datatables');
// Route::view('/pages/blank', 'pages.blank');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/accounts/admin_management/create.blade.php
@extends('admin.layouts.app')

@push('css_before')
<link rel="stylesheet" href="{{ asset('/js/plugins/select2/css/select2.min.css')}}">
@endpush

@section('content')
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                Create Account Admin<small class="font-size-base font-w400 text-muted">Create Account</small>
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="{{ route('admin.home')}}">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="{{ route('admin.admin_manager.index')}}">Admin Account</a></li>
                    <li class="breadcrumb-item" aria-current="page">
                        <a class="link-fx" href="{{ route('admin.admin_manager.create') }}">Create Account</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<div class="content">
    <div class="row">
        <div class="col-xl-12">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title">Create Account</h3>
                </div>
                <div class="block-content block-content-full">
                    {{ Form::open(['route' => 'admin.admin_manager.store', 'method' => 'post']) }}
                        <div class="row push">
                            <div class="col-lg-8 col-xl-5">
                                <div class="form-group">
                                    {{ Form::label('name', 'Name') }} <span class="text-danger">*</span>
                                    {{ Form::text('name', null, array('class' => 'form-control', 
                                        'id' => 'name', 
                                        'placeholder' => 'Name')) }}
                                    @error('name')
                                        <div class="alert alert-danger alert-dismissable" role="alert">
                                            <p class="mb-0">{{ $message }}</p>
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    {{ Form::label('email', 'Email') }} <span class="text-danger">*</span>
                                    {{ Form::text('email', null, array('class' => 'form-control', 
                                        'id' => 'email', 
                                        'placeholder' => 'Email')) }}
                                    @error('email')
                                        <div class="alert alert-danger alert-dismissable" role="alert">
                                            <p class="mb-0">{{ $message }}</p>
                                        </div>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    {{ Form::label('roles', 'Roles') }}
                                    {{ Form::select('roles[]', $roles->pluck('name', 'id'), null, ['class' => 'form-control', 'id' => 'roles', 'multiple' => true]) }}
                                </div>

                                <br>
                                <hr>

                                <div class="form-group">
                                    {{ Form::label('password', 'Password') }} <span class="text-danger">*</span>
                                    {{ Form::password('password', ['class' => 'form-control']) }}
                                    @error('password')
                                        <div class="alert alert-danger alert-dismissable" role="alert">
                                            <p class="mb-0">{{ $message }}</p>
                                        </div>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    {{ Form::label('password', 'Confirm Password') }} <span class="text-danger">*</span>
                                    {{ Form::password('password_confirmation', ['class' => 'form-control']) }}
                                </div>

                                
                                <hr>
                                <div class="form-group row">
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-block btn-primary">
                                            <i class="fa fa-fw fa-save mr-1"></i> Save
                                        </button>
                                    </div>
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-block btn-alt-secondary">
                                            <i class="fa fa-fw fa-times-circle mr-1"></i> Cancel
                                        </button>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script src="{{ asset('/js/plugins/select2/js/select2.full.min.js')}}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#roles').select2({placeholder:'', allowClear: true});
        });
    </script>
@endpush

resources/views/admin/accounts/admin_management/edit.blade.php
@extends('admin.layouts.app')

@push('css_before')
<link rel="stylesheet" href="{{ asset('/js/plugins/select2/css/select2.min.css')}}">
@endpush

@section('content')
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                Edit Account Admin<small class="font-size-base font-w400 text-muted">Edit Account</small>
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="{{ route('admin.home')}}">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="{{ route('admin.admin_manager.index')}}">Admin Account</a></li>
                    <li class="breadcrumb-item" aria-current="page">
                        <a class="link-fx" href="{{ route('admin.admin_manager.edit', $user->id) }}">Edit Account</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<div class="content">
    <div class="row">
        <div class="col-xl-12">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title">Edit Account</h3>
                </div>
                <div class="block-content block-content-full">
                    {{ Form::model($user, ['route' => ['admin.admin_manager.update', $user->id], 'method' => 'PUT']) }}
                        <div class="row push">
                            <div class="col-lg-8 col-xl-5">
                                <div class="form-group">
                                    {{ Form::label('name', 'Name') }} <span class="text-danger">*</span>
                                    {{ Form::text('name', null, array('class' => 'form-control', 
                                        'id' => 'name', 
                                        'placeholder' => 'Name')) }}
                                    @error('name')
                                        <div class="alert alert-danger alert-dismissable" role="alert">
                                            <p class="mb-0">{{ $message }}</p>
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    {{ Form::label('email', 'Email') }} <span class="text-danger">*</span>
                                    {{ Form::text('email', null, array('class' => 'form-control', 
                                        'id' => 'email', 
                                        'placeholder' => 'Email')) }}
                                    @error('email')
                                        <div class="alert alert-danger alert-dismissable" role="alert">
                                            <p class="mb-0">{{ $message }}</p>
                                        </div>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    {{ Form::label('roles', 'Roles') }}
                                    {{ Form::select('roles[]', $roles->pluck('name', 'id'), $user->roles->pluck('id')->toArray(), ['class' => 'form-control', 'id' => 'roles', 'multiple' => true]) }}
                                </div>

                                <br>
                                <hr>

                                <div class="form-group">
                                    {{ Form::label('password', 'Password') }}
                                    {{ Form::password('password', ['class' => 'form-control']) }}
                                    @error('password')
                                        <div class="alert alert-danger alert-dismissable" role="alert">
                                            <p class="mb-0">{{ $message }}</p>
                                        </div>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    {{ Form::label('password', 'Confirm Password') }}
                                    {{ Form::password('password_confirmation', ['class' => 'form-control']) }}
                                </div>

                                
                                <hr>
                                <div class="form-group row">
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-block btn-primary">
                                            <i class="fa fa-fw fa-save mr-1"></i> Save
                                        </button>
                                    </div>
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-block btn-alt-secondary">
                                            <i class="fa fa-fw fa-times-circle mr-1"></i> Cancel
                                        </button>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script src="{{ asset('/js/plugins/select2/js/select2.full.min.js')}}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#roles').select2({placeholder:'', allowClear: true});
        });
    </script>
@endpush

resources/views/admin/accounts/admin_management/index.blade.php
@extends('admin.layouts.app')

@push('css_before')
@endpush

@section('content')
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                Admin Account <small class="font-size-base font-w400 text-muted">Admin Account</small>
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">Dashboard</li>
                    <li class="breadcrumb-item" aria-current="page">
                        <a class="link-fx" href="{{ route('admin.admin_manager.index')}}">Account</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<div class="content">
    <div class="row">
        <div class="col-xl-12">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title">Admin Account</h3>
                    <div class="block-options">
                        <div class="block-options-item">
                            <code>
                                <a href="{{ route('admin.admin_manager.create')}}" class="btn btn-primary">Add</a>
                            </code>
                        </div>
                    </div>
                </div>
                <div class="block-content">
                    <table class="table table-vcenter">
                        <thead>
                            <tr>
                                <th class="text-center" style="width: 50px;">#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th class="d-none d-sm-table-cell">Roles</th>
                                <th class="text-center" style="width: 100px;">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                            <tr>
                                <th class="text-center" scope="row">1</th>
                                <td class="font-w600 font-size-sm">
                                    <a href="javascript void(0)">{{ $user->name }}</a>
                                </td>
                                <td class="font-w600 font-size-sm">
                                    {{ $user->email }}
                                </td>
                                <td class="d-none d-sm-table-cell">
                                    <span class="badge badge-success">{{ join(', ', $user->roles->pluck('name')->toArray()) }}</span>
                                </td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <a href="{{ route('admin.admin_manager.edit', $user->id) }}" class="btn btn-sm btn-light" data-toggle="tooltip" title="Edit User">
                                            <i class="fa fa-fw fa-pencil-alt"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                            @if($users->isEmpty())
                                <tr>
                                    <td colspan="4" class="text-center">{{__('Không có dữ liệu')}}</td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

@push('scripts')

@endpush