routes/admin.php
<?php

Route::name('admin.')->group(function () {
    Route::group(['namespace' => 'Admin'], function() {
        // Dashboard
        Route::get('/', 'HomeController@index')->name('home');
    
        // Login
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    
        // Register
        // Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('admin.register');
        // Route::post('register', 'Auth\RegisterController@register');
    
        // Reset Password
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
    
        // Confirm Password
        Route::get('password/confirm', 'Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
        Route::post('password/confirm', 'Auth\ConfirmPasswordController@confirm');
    
        // Verify Email
        // Route::get('email/verify', 'Auth\VerificationController@show')->name('admin.verification.notice');
        // Route::get('email/verify/{id}/{hash}', 'Auth\VerificationController@verify')->name('admin.verification.verify');
        // Route::post('email/resend', 'Auth\VerificationController@resend')->name('admin.verification.resend');
    
    
        Route::group(['namespace' => 'AccountManager', 'middleware' => ['admin.auth']], function() {
            Route::resource('roles','RoleController');
            Route::resource('permissions','PermissionController');
            Route::resource('admin_manager','AdminController');
        });
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Example Routes
Route::view('/', 'landing');

// Route::match(['get', 'post'], '/dashboard', function(){
//     return view('dashboard');
// });
// Route::view('/pages/slick', 'pages.slick');
// Route::view('/pages/datatables', 'pages.datatables');
// Route::view('/pages/blank', 'pages.blank');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/partials/menu.blade.php
<ul class="nav-main">
    <li class="nav-main-item">
        <a class="nav-main-link{{ request()->is('admin') ? ' active' : '' }}" href="{{ route('admin.home')}}">
            <i class="nav-main-link-icon si si-cursor"></i>
            <span class="nav-main-link-name">Dashboard</span>
        </a>
    </li>
    <li class="nav-main-heading">Account</li>

    <li class="nav-main-item{{ (request()->is('admin/roles') || request()->is('admin/permissions')) ? ' open' : '' }}">
        <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="true" href="#">
            <i class="nav-main-link-icon fa fa-user-lock"></i>
            <span class="nav-main-link-name">Roles/Permission</span>
        </a>
        <ul class="nav-main-submenu">
            <li class="nav-main-item">
                <a class="nav-main-link{{ request()->is('admin/roles/*') ? ' active' : '' }}" href="{{ route('admin.roles.index') }}">
                    <span class="nav-main-link-name">Role</span>
                </a>
            </li>
            <li class="nav-main-item">
                <a class="nav-main-link{{ request()->is('admin/permissions/*') ? ' active' : '' }}" href="{{ route('admin.permissions.index') }}">
                    <span class="nav-main-link-name">Permission</span>
                </a>
            </li>
        </ul>
    </li>
    <li class="nav-main-item{{ request()->is('admin/admin_manager/*') ? ' open' : '' }}">
        <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="true" href="#">
            <i class="nav-main-link-icon fa fa-users"></i>
            <span class="nav-main-link-name">Admin Account</span>
        </a>
        <ul class="nav-main-submenu">
            <li class="nav-main-item">
                <a class="nav-main-link{{ request()->is('admin/admin_manager') ? ' active' : '' }}" href="{{ route('admin.admin_manager.index') }}">
                    <span class="nav-main-link-name">All Account</span>
                </a>
            </li>
        </ul>
    </li>
    
    {{-- <li class="nav-main-item{{ request()->is('pages/*') ? ' open' : '' }}">
        <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="true" href="#">
            <i class="nav-main-link-icon si si-bulb"></i>
            <span class="nav-main-link-name">Examples</span>
        </a>
        <ul class="nav-main-submenu">
            <li class="nav-main-item">
                <a class="nav-main-link{{ request()->is('pages/datatables') ? ' active' : '' }}" href="/pages/datatables">
                    <span class="nav-main-link-name">DataTables</span>
                </a>
            </li>
            <li class="nav-main-item">
                <a class="nav-main-link{{ request()->is('pages/slick') ? ' active' : '' }}" href="/pages/slick">
                    <span class="nav-main-link-name">Slick Slider</span>
                </a>
            </li>
            <li class="nav-main-item">
                <a class="nav-main-link{{ request()->is('pages/blank') ? ' active' : '' }}" href="/pages/blank">
                    <span class="nav-main-link-name">Blank</span>
                </a>
            </li>
        </ul>
    </li>  --}}
    {{-- <li class="nav-main-heading">More</li>
    <li class="nav-main-item open">
        <a class="nav-main-link" href="/">
            <i class="nav-main-link-icon si si-globe"></i>
            <span class="nav-main-link-name">Landing</span>
        </a>
    </li> --}}
</ul>