routes/admin.php
<?php

Route::name('admin.')->group(function () {
    Route::group(['namespace' => 'Admin'], function() {
        // Dashboard
        Route::get('/', 'HomeController@index')->name('home');
    
        // Login
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    
        // Register
        // Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('admin.register');
        // Route::post('register', 'Auth\RegisterController@register');
    
        // Reset Password
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
    
        // Confirm Password
        Route::get('password/confirm', 'Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
        Route::post('password/confirm', 'Auth\ConfirmPasswordController@confirm');
    
        // Verify Email
        // Route::get('email/verify', 'Auth\VerificationController@show')->name('admin.verification.notice');
        // Route::get('email/verify/{id}/{hash}', 'Auth\VerificationController@verify')->name('admin.verification.verify');
        // Route::post('email/resend', 'Auth\VerificationController@resend')->name('admin.verification.resend');
    
    
        Route::group(['namespace' => 'AccountManager', 'middleware' => ['admin.auth']], function() {
            Route::resource('roles','RoleController');
            Route::resource('permissions','PermissionController');
            Route::resource('admin_manager','AdminController');
        });
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Example Routes
Route::view('/', 'landing');

// Route::match(['get', 'post'], '/dashboard', function(){
//     return view('dashboard');
// });
// Route::view('/pages/slick', 'pages.slick');
// Route::view('/pages/datatables', 'pages.datatables');
// Route::view('/pages/blank', 'pages.blank');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/AccountManager/RoleController.php
<?php
namespace App\Http\Controllers\Admin\AccountManager;

use Illuminate\Http\Request;
use App\Http\Controllers\Admin\BaseController;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;


class RoleController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('admin_permission:role-list|role-create|role-edit|role-delete', ['only' => ['index','store']]);
        $this->middleware('admin_permission:role-create', ['only' => ['create','store']]);
        $this->middleware('admin_permission:role-edit', ['only' => ['edit','update']]);
        $this->middleware('admin_permission:role-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = Role::orderBy('id','DESC')->paginate(5);
        return view('admin.accounts.roles.index',compact('roles'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::orderBy('name')->get();
        $guards = config('custom.guards');
        return view('admin.accounts.roles.create',compact('permissions', 'guards'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
                'name' => 'required|unique:roles',
                'guard_name' => 'required',
            ]
        );

        $name = $request->input('name');
        $role = new Role();
        $role->name = $name;
        $role->guard_name = $request->input('guard_name');
        $permissions = $request->input('permissions', []);
        $role->save();
        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->first();
            $role = Role::where('name', '=', $name)->first();
            $p && $role->givePermissionTo($p);
        }

        return redirect()->route('admin.roles.index')
                        ->with('success','Role created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return \abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $guards = config('custom.guards');
        $role = Role::findOrFail($id);
        $permissions = Permission::orderBy('name')->get();
        return view('admin.accounts.roles.edit', compact('role', 'permissions', 'guards'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::findOrFail($id);
        $this->validate($request, [
            'name' => 'required|unique:roles,name,' . $id,
            'guard_name' => 'required',
        ]);

        $permissions = $request->input('permissions', []);
        $role->name = $request->input('name');
        $role->guard_name = $request->input('guard_name');
        $role->save();

        $p_all = Permission::all();
        foreach ($p_all as $p) {
            $role->revokePermissionTo($p);
        }
        foreach ($permissions as $permission) {
            $p = Permission::where(['id' => $permission, 'guard_name' => $role->guard_name])->first();
            $p && $role->givePermissionTo($p);
        }

        return redirect()->route('admin.roles.index')
                        ->with('success','Role updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();
        return redirect()->route('admin.roles.index')
                        ->with('success','Role deleted successfully');
    }
}

resources/views/admin/accounts/roles/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                Create Role <small class="font-size-base font-w400 text-muted">Role</small>
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="{{ route('admin.home')}}">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="{{ route('admin.roles.index')}}">Roles</a></li>
                    <li class="breadcrumb-item" aria-current="page">
                        <a class="link-fx" href="{{ route('admin.roles.create') }}">Create Role</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<div class="content">
    <div class="row">
        <div class="col-xl-12">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title">Create Role</h3>
                </div>
                <div class="block-content block-content-full">
                    {{ Form::open(['route' => 'admin.roles.store', 'method' => 'post']) }}
                        <div class="row push">
                            <div class="col-lg-8 col-xl-5">
                                <div class="form-group">
                                    {{ Form::label('role_name', 'Name') }} <span class="text-danger">*</span>
                                    {{ Form::text('name', null, array('class' => 'form-control', 
                                        'id' => 'role_name', 
                                        'placeholder' => 'Role Name')) }}
                                </div>
                                <div class="form-group">
                                    {{ Form::label('role_guard', 'Guard') }} <span class="text-danger">*</span>
                                    {{ Form::select('guard_name', $guards, null, array('class' => 'form-control', 'id' => 'role_guard')) }}
                                </div>
                                @if(!$permissions->isEmpty())
                                    <div class="form-group box-permission">
                                        <label>Permissions</label>
                                        <div class="form-check">
                                            {{ Form::checkbox('permissions[]',  null, null, ['id' => 'permission_all', 'class' => 'form-check-input']) }}
                                            {{ Form::label('permission_all', __('Tất cả'), ['class' => 'form-check-label']) }}
                                        </div>
                                        @foreach ($permissions as $permission)
                                            <div class="form-check guard_item {{'guard_' . $permission->guard_name}}">
                                                {{ Form::checkbox('permissions[]',  $permission->id, null, ['id' => 'permission_' . $permission->id, 'class' => 'form-check-input permission_checkbox']) }}
                                                {{ Form::label('permission_' . $permission->id, ucfirst($permission->name), ['class' => 'form-check-label']) }}
                                            </div>
                                        @endforeach
                                    </div>
                                @endif
                                <hr>
                                <div class="form-group row">
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-block btn-primary">
                                            <i class="fa fa-fw fa-save mr-1"></i> Save
                                        </button>
                                    </div>
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-block btn-alt-secondary">
                                            <i class="fa fa-fw fa-times-circle mr-1"></i> Cancel
                                        </button>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script type="text/javascript">
        var displayPermission = function () {

            var guard_name = 'guard_'+$('select[name=guard_name]').val();

            $('.guard_item').hide();
            $('.box-permission .guard_item input').prop('disabled', true);
            $('.box-permission .guard_item input').prop('checked', false);

            //show in guard
            $('.'+guard_name).show();
            $('.box-permission .'+guard_name+' input').prop('disabled', false);
            $('#permission_all').prop('checked', false);
        };

        var checkAllStatus = function(){
            var permissionCount = $('.permission_checkbox').not(':disabled').length;
            var permissionSelectedCount = $('.permission_checkbox:checked').length;
            $('#permission_all').prop('checked', permissionCount === permissionSelectedCount);
        };

        $(document).ready(function () {
            displayPermission();
            checkAllStatus();

            $('select[name=guard_name]').change(displayPermission);

            $('#permission_all').change(function () {
                $(this).closest('.box-permission').find('input:checkbox').not(this).not(':disabled').prop('checked', this.checked);
            });

            $('.permission_checkbox').change(checkAllStatus);
        });
    </script>
@endpush

resources/views/admin/accounts/roles/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                Edit Role <small class="font-size-base font-w400 text-muted">Role</small>
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="{{ route('admin.home')}}">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="{{ route('admin.roles.index')}}">Roles</a></li>
                    <li class="breadcrumb-item" aria-current="page">
                        <a class="link-fx" href="{{ route('admin.roles.edit', $role->id) }}">Edit Role</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<div class="content">
    <div class="row">
        <div class="col-xl-12">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title">Edit Role</h3>
                </div>
                <div class="block-content block-content-full">
                    {{ Form::model($role, ['route' => ['admin.roles.update', $role->id], 'method' => 'PUT']) }}
                        <div class="row push">
                            <div class="col-lg-8 col-xl-5">
                                <div class="form-group">
                                    {{ Form::label('role_name', 'Name') }} <span class="text-danger">*</span>
                                    {{ Form::text('name', null, array('class' => 'form-control', 
                                        'id' => 'role_name', 
                                        'placeholder' => 'Role Name')) }}
                                </div>
                                <div class="form-group">
                                    {{ Form::label('role_guard', 'Guard') }} <span class="text-danger">*</span>
                                    {{ Form::select('guard_name', $guards, null, array('class' => 'form-control', 'id' => 'role_guard')) }}
                                </div>
                                @if(!$permissions->isEmpty())
                                    <div class="form-group box-permission">
                                        <label>Permissions</label>
                                        <div class="form-check">
                                            {{ Form::checkbox('permissions[]',  null, null, ['id' => 'permission_all', 'class' => 'form-check-input']) }}
                                            {{ Form::label('permission_all', __('Tất cả'), ['class' => 'form-check-label']) }}
                                        </div>
                                        @foreach ($permissions as $permission)
                                            <div class="form-check guard_item {{'guard_' . $permission->guard_name}}">
                                                {{ Form::checkbox('permissions[]',  $permission->id, $role->permissions, ['id' => 'permission_' . $permission->id, 'class' => 'form-check-input permission_checkbox']) }}
                                                {{ Form::label('permission_' . $permission->id, ucfirst($permission->name), ['class' => 'form-check-label']) }}
                                            </div>
                                        @endforeach
                                    </div>
                                @endif
                                <hr>
                                <div class="form-group row">
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-block btn-primary">
                                            <i class="fa fa-fw fa-save mr-1"></i> Save
                                        </button>
                                    </div>
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-block btn-alt-secondary">
                                            <i class="fa fa-fw fa-times-circle mr-1"></i> Cancel
                                        </button>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script type="text/javascript">
        var displayPermission = function (change = false) {

            var guard_name = 'guard_'+$('select[name=guard_name]').val();

            $('.guard_item').hide();
            $('.box-permission .guard_item input').prop('disabled', true);
            if(change) {
                $('.box-permission .guard_item input').prop('checked', false);
            }

            //show in guard
            $('.'+guard_name).show();
            $('.box-permission .'+guard_name+' input').prop('disabled', false);
            $('#permission_all').prop('checked', false);
        };

        var checkAllStatus = function(){
            var permissionCount = $('.permission_checkbox').not(':disabled').length;
            var permissionSelectedCount = $('.permission_checkbox:checked').length;
            $('#permission_all').prop('checked', permissionCount === permissionSelectedCount);
        };

        $(document).ready(function () {
            displayPermission();
            checkAllStatus();

            $('select[name=guard_name]').change(function(){
                displayPermission(true)
            });

            $('#permission_all').change(function () {
                $(this).closest('.box-permission').find('input:checkbox').not(this).not(':disabled').prop('checked', this.checked);
            });

            $('.permission_checkbox').change(checkAllStatus);
        });
    </script>
@endpush

resources/views/admin/accounts/roles/index.blade.php
@extends('admin.layouts.app')

@push('css_before')
<link rel="stylesheet" href="{{ asset('/js/plugins/sweetalert2/sweetalert2.min.css')}}">
@endpush

@section('content')
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                Roles <small class="font-size-base font-w400 text-muted">Role</small>
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">Dashboard</li>
                    <li class="breadcrumb-item" aria-current="page">
                        <a class="link-fx" href="{{ route('admin.roles.index')}}">Roles</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<div class="content">
    <div class="row">
        <div class="col-xl-12">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title">Roles</h3>
                    <div class="block-options">
                        <div class="block-options-item">
                            <code>
                                <a href="{{ route('admin.roles.create')}}" class="btn btn-primary">Add</a>
                            </code>
                        </div>
                    </div>
                </div>
                <div class="block-content">
                    <table class="table table-vcenter">
                        <thead>
                            <tr>
                                <th class="text-center" style="width: 50px;">#</th>
                                <th>Name</th>
                                <th>Guard</th>
                                <th class="d-none d-sm-table-cell">Permission</th>
                                <th class="text-center" style="width: 100px;">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($roles as $role)
                            <tr>
                                <th class="text-center" scope="row">1</th>
                                <td class="font-w600 font-size-sm">
                                    <a href="javascript void(0)">{{ $role->name }}</a>
                                </td>
                                <td class="d-none d-sm-table-cell">
                                    <span class="badge badge-success">{{ $role->guard_name }}</span>
                                </td>
                                <td>
                                    {{  $role->permissions()->pluck('name')->implode(', ') }}
                                </td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <a href="{{ route('admin.roles.edit', $role->id) }}" class="btn btn-sm btn-light" data-toggle="tooltip" title="Edit Role">
                                            <i class="fa fa-fw fa-pencil-alt"></i>
                                        </a>
                                        <button type="button" class="btn btn-sm btn-light btn-delete-role" data-role_id="{{$role->id}}" data-toggle="tooltip" title="Remove Role">
                                            <i class="fa fa-fw fa-times"></i>
                                        </button>
                                        {!! Form::open(['method' => 'DELETE', 'route' => ['admin.roles.destroy', $role->id], 'id' => 'form-delete-' . $role->id ]) !!}
                                        {!! Form::close() !!}
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

@push('scripts')
<!-- Page JS Plugins -->
<script src="{{ asset('/js/plugins/es6-promise/es6-promise.auto.min.js')}}"></script>
<script src="{{ asset('/js/plugins/sweetalert2/sweetalert2.min.js')}}"></script>

<script>
    $(function(){
        // Set default properties
        let toast = Swal.mixin({
            buttonsStyling: false,
            customClass: {
                confirmButton: 'btn btn-success m-1',
                cancelButton: 'btn btn-danger m-1',
                input: 'form-control'
            }
        });

        $(document).on('click', '.btn-delete-role', function(){
            var id =  $(this).data('role_id');
            toast.fire({
                title: 'Are you sure?',
                text: 'You will not be able to recover this role!',
                icon: 'warning',
                showCancelButton: true,
                customClass: {
                    confirmButton: 'btn btn-danger m-1',
                    cancelButton: 'btn btn-secondary m-1'
                },
                confirmButtonText: 'Yes, delete it!',
                html: false,
                preConfirm: e => {
                    $('#form-delete-'+id).submit();
                }
            }).then(result => {
                if (result.value) {
                    toast.fire('Deleted!', 'Role has been deleted.', 'success');
                    // result.dismiss can be 'overlay', 'cancel', 'close', 'esc', 'timer'
                } else if (result.dismiss === 'cancel') {
                    toast.fire('Cancelled', 'Role is safe :)', 'error');
                }
            });
        });
    });
</script>
@endpush